
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Ubuntu_Mono, Crimson_Text } from 'next/font/google'

import "./globals.css";
import { Providers } from "@/app/components/theme-providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configure Ubuntu Mono for code/monospace text
const ubuntuMono = Ubuntu_Mono({
  weight: ['400', '700'], // Regular and Bold
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ubuntu-mono',
})

// Configure Crimson Text for headings and body
const crimsonText = Crimson_Text({
  weight: ['400', '600', '700'], // Regular, Semi-bold, Bold
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-crimson-text',
})

export const metadata: Metadata = {
  title: "marcoco's web portfolio",
  description: "Generated by Sofi & Tur!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en" 
      className={`${crimsonText.variable} ${ubuntuMono.variable}`}
      suppressHydrationWarning
    >
      <body className={crimsonText.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
