import type { Metadata } from "next";
import { Ubuntu_Mono, Crimson_Text } from "next/font/google";
import CustomCursor from "./components/ui/CustomCursor";

import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

import "./globals.css";
import { Providers } from "@/src/app/components/theme-providers";

// Configure Ubuntu Mono for code/monospace text
const ubuntuMono = Ubuntu_Mono({
  weight: ["400", "700"], // Regular and Bold
  subsets: ["latin"],
  display: "swap",
  variable: "--font-ubuntu-mono",
});

// Configure Crimson Text for headings and body
const crimsonText = Crimson_Text({
  weight: ["400", "600", "700"], // Regular, Semi-bold, Bold
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-crimson-text",
});

export const metadata: Metadata = {
  title: "marcoco's web portfolio",
  description: "Generated by Sofi & Tur!",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html
      lang={locale}
      className={`${crimsonText.variable} ${ubuntuMono.variable}`}
      suppressHydrationWarning
    >
      <body className={crimsonText.className}>
        <NextIntlClientProvider>
          <CustomCursor />
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
